name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.402
        msbuild-version: 17.0.x  # Specify the version of MSBuild here
    - name: Restore dependencies
      run: dotnet restore
    - name: Build z1g Project Hub Universal
      run: dotnet build "z1g Project Hub Universal\z1g Project Hub Universal.vbproj" --configuration Release
    - name: Build z1g Setup
      run: dotnet build update/update.vbproj --no-restore
    - name: Build Terbium
      run: dotnet build Terbium/Terbium.csproj --no-restore
    - name: Build Velocity
      run: dotnet build Velocity/velocity.csproj --no-restore
    - name: Build z1g Browser
      run: dotnet build "z1g Browser/z1g Browser.csproj" --no-restore
    # Add more build steps for other projects as needed
    - name: Test
      run: dotnet test --no-build --verbosity normal
