name: Nightly Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Test
        run: |
          dotnet build --configuration Release
          dotnet test

      - name: Publish Nightly Build
        env:
          COMMIT_HASH: ${{ github.sha }}
          TAG_NAME: ${{ github.ref }}
          NIGHTLY_BUILD_VERSION: ${{ format('nightly-{0:MMddyy-HHmm}-{1}', github.event.repository.pushed_at, github.sha) }}
        run: |
          dotnet publish --configuration Release --output publish/
          cd publish/
          zip -r nightly-build.zip .
          echo "::set-output name=nightly_build_version::${NIGHTLY_BUILD_VERSION}"
