name: Nightly Builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *' # Run at midnight every day

jobs:
  create_tag:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d-%Y')"

      - name: Build z1g Project Hub Universal
        run: dotnet build "z1g Project Hub Universal\z1g Project Hub Universal.vbproj" --configuration Release

      - name: Publish z1g Project Hub Universal
        run: dotnet publish "z1g Project Hub Universal\z1g Project Hub Universal.vbproj" --configuration Release --output ./publish

      - name: Create ZIP file
        run: |
          7z a -tzip compiled-zips/z1g-project-hub.zip ./publish/*
          mv compiled-zips/z1g-project-hub.zip compiled-zips/

      - name: Create tag
        id: create_tag
        run: |
          echo "z1g-hub-nightly-${{ steps.date.outputs.date }}" > tag.txt
          git tag -a -F tag.txt "z1g-hub-nightly-${{ steps.date.outputs.date }}"
          git push origin "z1g-hub-nightly-${{ steps.date.outputs.date }}"

      - name: Upload compiled ZIP as tag asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_tag.outputs.id }}/assets{?name,label}
          asset_path: compiled-zips/z1g-project-hub.zip
          asset_name: z1g-project-hub.zip
          asset_content_type: application/zip

      - name: Read changelog file
        id: changelog
        run: |
          changelog=$(cat nightlychangelogs.md)
          echo "::set-output name=changelog::$changelog"

      - name: Update tag description with changelog
        run: |
          git fetch --tags
          tag_sha=$(git rev-list -n 1 "z1g-hub-nightly-${{ steps.date.outputs.date }}")
          git tag -a -f -m "${{ steps.changelog.outputs.changelog }}" "${{ steps.date.outputs.date }}" $tag_sha
          git push --tags
