name: Nightly Builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *' # Run at midnight every day

jobs:
  create_tag:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d-%Y')"

      - name: Build z1g Project Hub Universal
        run: dotnet build "z1g Project Hub Universal\z1g Project Hub Universal.vbproj" --configuration Release

      - name: Publish z1g Project Hub Universal
        run: dotnet publish "z1g Project Hub Universal\z1g Project Hub Universal.vbproj" --configuration Release --output ./publish

      - name: Create ZIP file
        run: |
          7z a -tzip z1g-project-hub.zip ./publish/*
          mv z1g-project-hub.zip compiled-zips/

      - name: Create tag
        run: |
          echo "z1g-hub-nightly-${{ steps.date.outputs.date }}" > tag.txt
          git tag -a -F tag.txt "z1g-hub-nightly-${{ steps.date.outputs.date }}"
          git push --tags

      - name: Create ZIP file
        run: |
          7z a -tzip compiled-zips/z1g-project-hub.zip "z1g Project Hub Universal/bin/Release/*"
          7z a -tzip compiled-zips/z1g-project-hub.zip "Terbium/bin/Release/*"
          7z a -tzip compiled-zips/z1g-project-hub.zip "Velocity/bin/Release/*"
          7z a -tzip compiled-zips/z1g-project-hub.zip "z1g Browser/bin/Release/*"

      - name: Upload compiled ZIP
        uses: actions/upload-artifact@v2
        with:
          name: compiled-zip
          path: compiled-zips/z1g-project-hub.zip
